# Generated by Django 3.0.4 on 2020-03-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=120)),
                ('confirmed', models.PositiveIntegerField()),
                ('active', models.PositiveIntegerField()),
                ('new_cases', models.PositiveIntegerField()),
                ('deaths', models.PositiveIntegerField()),
                ('new_deaths', models.PositiveIntegerField()),
                ('recovered', models.PositiveIntegerField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
