# Generated by Django 3.0.4 on 2020-04-06 17:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pop2005', models.IntegerField(verbose_name='Population 2005')),
                ('iso2', models.CharField(max_length=2, verbose_name='2 Digit ISO')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlerCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.IntegerField()),
                ('active', models.IntegerField()),
                ('new_cases', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('new_deaths', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrawledData.Country')),
            ],
        ),
    ]
