# Generated by Django 3.0.4 on 2020-03-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrawledData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlercovid',
            name='active',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crawlercovid',
            name='confirmed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crawlercovid',
            name='new_cases',
            field=models.IntegerField(default=0),
        ),
    ]
