# Generated by Django 3.0.4 on 2020-04-06 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CrawledData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlercovid',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CrawledData.Country'),
        ),
    ]
