# Generated by Django 3.0.4 on 2020-03-27 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrawledData', '0002_auto_20200326_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlercovid',
            name='last_update',
        ),
    ]
