# Generated by Django 3.0.4 on 2020-03-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrawledData', '0003_remove_crawlercovid_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlercovid',
            name='active',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='crawlercovid',
            name='confirmed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='crawlercovid',
            name='deaths',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='crawlercovid',
            name='new_cases',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='crawlercovid',
            name='new_deaths',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='crawlercovid',
            name='recovered',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='crawlercovid',
            name='updated_at',
            field=models.PositiveIntegerField(),
        ),
    ]
