# Generated by Django 3.0.4 on 2020-03-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrawledData', '0004_auto_20200326_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlercovid',
            name='new_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlercovid',
            name='new_deaths',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
