# Generated by Django 3.0.4 on 2020-03-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrawledData', '0005_auto_20200326_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlercovid',
            name='deaths',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlercovid',
            name='recovered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlercovid',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
