# Generated by Django 3.0.4 on 2020-03-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('country', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('total_cases', models.IntegerField()),
                ('active_cases', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
            ],
        ),
    ]
