# Generated by Django 3.0.4 on 2020-03-23 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('country', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('confirmed', models.PositiveIntegerField(default=0)),
                ('active', models.PositiveIntegerField(default=0)),
                ('new_cases', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('new_deaths', models.PositiveIntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cases', models.PositiveIntegerField(default=0)),
                ('new_deaths', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('WA', 'Waiting Approval'), ('A', 'Approved'), ('R', 'Rejected')], default='WA', help_text='Source Status', max_length=2)),
                ('source', models.URLField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
