# Generated by Django 3.0.4 on 2020-03-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20200323_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(),
        ),
    ]
