# Generated by Django 3.0.4 on 2020-03-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200323_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
    ]
